### ISSUE TITLE
TradingBot Repo.

### ISSUE THREAD

**Issue by eddyelly** [claymachinegun/TradingBot#1]
please help me It gives me this error "a project with an output type of class library cannot be started directly in visual studio"  even though i select a startup.

**Comment by claymachinegun** [comment]
> please help me It gives me this error "a project with an output type of class library cannot be started directly in visual studio" even though i select a startup.

You should use .net core toolkit to build and run it, like so:
```
$ cd TelegramAdvisor/
$ dotnet run
```

It's been a while, since I wrote it, so this project is kinda outdated. Feel free to do whatever you want with it.
